{% set name = "tiatoolbox" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 52e2164f7297ca0db47a2943f01a11d6c658cf9021442943f93ae0248b175932

build:
  number: 2
  noarch: python
  entry_points:
    - tiatoolbox=tiatoolbox.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
    - opencv >=4.5.5
  run:
    - albumentations >=1.0.3
    - click >=8.1.2
    - cudatoolkit >=11.3
    - defusedxml >=0.7.1
    - flask >=2.1.1
    - glymur >=0.9.9
    - imagecodecs >=2021.11.20
    - joblib >=1.1.0
    - jupyterlab >=3.4.0
    - matplotlib-base >=3.5.1
    - numpy >=1.21.5
    - opencv >=4.5.5
    - openjpeg >=2.4.0
    - openslide-python >=1.1.2
    - pandas >=1.3.5
    - pillow >=9.0.1
    - pydicom >=2.3.0
    - python >=3.7
    - pytorch >=1.11.0
    - pyyaml >=6.0
    - requests >=2.27.1
    - scikit-image >=0.19.2
    - scikit-learn >=1.0.2
    - scipy >=1.7.3
    - shapely >=1.8.1
    - SimpleITK >=2.1.1
    - sphinx >=4.3.2
    - tifffile >=2021.11.2
    - torchvision >=0.12.0
    - tqdm >=4.63.1
    - umap-learn >=0.5.2
    - wsidicom >=0.2.0
    - zarr >=2.11.1

test:
  imports:
    - tiatoolbox
    - tiatoolbox.annotation
  commands:
    - tiatoolbox --help
  requires:
    - pip

about:
  home: https://github.com/TissueImageAnalytics/tiatoolbox
  summary: Computational pathology toolbox developed by TIA Lab.
  license: BSD-3-Clause
  license_file: {{ RECIPE_DIR if RECIPE_DIR is defined else '' }}/LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - shaneahmed
    - John-P
